runTomeCanoUser:
	python3 Programa.py ./Data/TomeCano.csv 1 
runTomeCanoServerBR:
	python3 Programa.py ./Data/TomeCano.csv 0 1 1 12 ./FinalImage_BR.png
runTomeCanoServerDTR:
	python3 Programa.py ./Data/TomeCano.csv 0 2 1 12 ./FinalImage_DTR.png
runTomeCanoServerMS:
	python3 Programa.py ./Data/TomeCano.csv 0 3 4 6 ./FinalImage_MS.png
run:
	python3 Programa.py $(file) 0 $(tipoGrafica) $(columnaSeleccionadaInicial) $(columnaSeleccionada) $(fileExit)