apiVersion: apps/v1
kind: Deployment # Modificar a StatefulSet (aplicacion con persistencia)
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pierresimt/backend-cn
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/Get/Methods
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    ports:
    - port: 3000
      targetPort: 3000
    selector:
      app: backend
 